---
title: "Chapter 4"
author: "Nick Lauerman"
date: "Started 15 May 2020"
output: 
  pdf_document: 
    fig_caption: yes
    fig_height: 6.5
    fig_width: 6.5
    number_sections: yes
    toc: yes
    toc_depth: 5
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Data Setup
From Adendex C
```{r}
text.v <- scan(file = "./SupportingMaterials/data/plainText/melville.txt",
               what = "character",
               sep = "\n")
start.v <- which(text.v == "CHAPTER 1. Loomings.")
end.v <- which(text.v == "orphan.")
novel.lines.v <- text.v[start.v:end.v]
novel.v <- paste(novel.lines.v,
                 collapse = " ")
novel.lower.v <- tolower(novel.v)
moby.words.l <- strsplit(novel.lower.v,
                         "\\W")
moby.word.v <- unlist(moby.words.l)
not.blanks.v <- which(moby.word.v != "")
moby.word.v <- moby.word.v[not.blanks.v]

```

# Dispersion Plot
```{r}
n.time.v <- seq(1:length(moby.word.v))
whales.v <- which(moby.word.v == "whale")
w.count.v <- rep(NA, length(n.time.v))
w.count.v[whales.v] <- 1
plot(w.count.v,
     main = "Dispersion Plot of 'Whale' in Mobey Dick",
     xlab = "Novel Time",
     ylab = "whale",
     type = "h",
     ylim = c(0,1),
     yaxt = 'n')

ahabs.v <- which(moby.word.v == "ahab")
a.count.v <- rep(NA, length(n.time.v))
a.count.v[ahabs.v] <- 1
plot(a.count.v,
     main = "Dispersion Plot of 'ahab' in Mobey Dick",
     xlab = "Novel Time",
     ylab = "ahab",
     type = "h",
     ylim = c(0,1),
     yaxt = 'n')
```

# Searching with *grep*
## Clearing the workspace
```{r}
rm(list = ls())
ls()
text.v <- scan(file = "./SupportingMaterials/data/plainText/melville.txt",
               what = "character",
               sep = "\n")
start.v <- which(text.v == "CHAPTER 1. Loomings.")
end.v <- which(text.v == "orphan.")
novel.lines.v <- text.v[start.v:end.v]

```

## Identify the chapter break positions in the vector using the *grep* function
```{r}
chap.positions.v <- grep("^CHAPTER \\d", novel.lines.v)
novel.lines.v[chap.positions.v]
chap.positions.v
novel.lines.v <- c(novel.lines.v,
                   "END")
last.position.v <- length(novel.lines.v)
chap.positions.v <- c(chap.positions.v,
                      last.position.v)
chap.positions.v
```

# The *for* Loop and *if* Conditional
```{r}
chap.positions.v[1]
chap.positions.v[2]

for (i in 1:length(chap.positions.v)) {
  print(chap.positions.v[i])
}

for (i in 1:length(chap.positions.v)) {
  print(paste("Chapter ",
              i,
              " begins at position ",
              chap.positions.v[i],
              sep = ""))
}

chapter.raws.l <- list()
chapter.freqs.l <- list()

for (i in 1:length(chap.positions.v)) {
  if(i != length(chap.positions.v)){
    chapter.title <- novel.lines.v[chap.positions.v[i]]
    start <- chap.positions.v[i] + 1
    end <- chap.positions.v[i + 1] - 1
    chapter.lines.v <- novel.lines.v[start:end]
    chapter.words.v <- tolower(paste(chapter.lines.v,
                                     collapse = " "))
    chapter.words.l <- strsplit(chapter.words.v, "\\W")
    chapter.words.v <- unlist(chapter.words.l)
    chapter.words.v <- chapter.words.v[which(chapter.words.v != "")]
    chapter.freq.t <- table(chapter.words.v)
    chapter.raws.l[[chapter.title]] <- chapter.freq.t
    chapter.freqs.t.rel <- 100 * (chapter.freq.t/sum(chapter.freq.t))
    chapter.freqs.l[[chapter.title]] <- chapter.freqs.t.rel
  }
}

```

# Accessing and Processing List Items
## *rbind* 
```{r}
x <- c(1,2,3,4,5)
y <- c(6,7,8,9,10)

rbind(x,y)

y <- c(6,7,8,9,10,11)
rbind(x,y)

```

## more recycling
```{r}
x <- c(1,2,3,4,5,6)
y <- 2
x*y
y <- c(2,3)
x*y
```

## *apply*
```{r}
#chapter.freqs.l
#chapter.raws.l

x <- list(a = 1:10,
          b = 2:25,
          b = 100:1090)
lapply(x, mean)

chapter.freqs.l[[1]]["whale"]

lapply(chapter.freqs.l, '[', 'whale')
whale.l <- lapply(chapter.freqs.l, '[', 'whale')
rbind(whale.l[[1]], 
      whale.l[[2]],
      whale.l[[3]])
```

## *do.call* (Do Dot Call)

```{r}
x <- list(1:3,4:6,7:9)
x
do.call(rbind,x)
whales.m <- do.call(rbind, whale.l)
whales.m

ahab.l <- lapply(chapter.freqs.l, '[', 'ahab')
ahabs.m <- do.call(rbind, ahab.l)
ahabs.m
```

## *cbind*
```{r}
class(whales.m)
class(whales.m[,1])
x <- c(1,2,3,4,5,6)
y <- c(2,4,5,6,7,8)
z <- c(24,23,34,32,12,10)
test.m <- cbind(x,y,z)
test.m
test.m[2,3]
test.m[2,]
test.m[,1]
test.m[,"y"]

whales.v <- whales.m[,1]
ahabs.v <- ahabs.m[,1]
whales.ahabs.m <- cbind(whales.v, ahabs.v)
dim(whales.ahabs.m)
colnames(whales.ahabs.m) <- c("whale","ahab")
barplot(whales.ahabs.m,
        beside = TRUE,
        col = "gray")
```

# Exercises
## 1
```{r}
queequeg.l <- lapply(chapter.freqs.l, '[' , 'queequeg')
queequeg.m <- do.call(rbind, queequeg.l)
queequeg.v <- queequeg.m[,1]
whales.ahab.queequeg.m <- cbind(whales.v, ahabs.v, queequeg.v)
colnames(whales.ahab.queequeg.m) <- c("whale",
                                      "ahab",
                                      "queequeg")
barplot(whales.ahab.queequeg.m,
        beside = TRUE,
        col = "gray")

```

## 2
```{r}

whale.raw.l <- lapply(chapter.raws.l, '[' , 'whale')
whale.raw.m <- do.call(rbind, whale.raw.l)
whale.raw.v <- as.vector(whale.raw.m[,1])

ahab.raw.l <- lapply(chapter.raws.l, '[' , 'ahab')
ahab.raw.m <- do.call(rbind, ahab.raw.l)
ahab.raw.v <- as.vector(ahab.raw.m[,1])

whale.ahab.raw.m <- cbind(whale.raw.v, ahab.raw.v)
colnames(whale.ahab.raw.m) <- c("whale",
                                "ahab")

barplot(whale.ahab.raw.m,
        beside = TRUE,
        col = "blue")
```