---
title: "Chapter 3"
author: "Nick Lauerman"
date: "Started 11-Mar-2020"
output: 
  pdf_document: 
    fig_caption: yes
    fig_height: 6.5
    fig_width: 6.5
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r required}
text.v <- scan(file = "./SupportingMaterials/data/plainText/melville.txt",
               what = "character",
               sep = "\n")
start.v <- which(text.v == "CHAPTER 1. Loomings.")
end.v <- which(text.v == "orphan.")
start.metadata.v <- text.v[1:start.v-1]
end.metadata.v <- text.v[end.v+1:length(text.v)]
novel.lines.v <- text.v[start.v:end.v]
metadata.v <- c(text.v[1:(start.v-1)],
                text.v[(end.v+1):length(text.v)])
novel.v <- paste(novel.lines.v,
                 collapse = " ")
novel.lower.v <- tolower(novel.v)
moby.words.l <- strsplit(novel.lower.v,
                         "\\W")
moby.word.v <- unlist(moby.words.l)
not.blanks.v <- which(moby.word.v != "")



moby.word.v <- moby.word.v[not.blanks.v]
whale.hits.v <- length(which(moby.word.v == "whale"))
total.words.v <- length(moby.word.v)
moby.fraqs.t <- table(moby.word.v)
sorted.moby.fraq.t <- sort(moby.fraqs.t,
                           decreasing = TRUE)
```


# Accessing Word Data
```{r}
sorted.moby.fraq.t["he"]
sorted.moby.fraq.t["she"]
sorted.moby.fraq.t["him"]
sorted.moby.fraq.t["her"]

sorted.moby.fraq.t["him"] / sorted.moby.fraq.t["her"]
sorted.moby.fraq.t["he"] / sorted.moby.fraq.t["she"]

length(moby.word.v)
sum(sorted.moby.fraq.t)
```

# Recycling
```{r}
sorted.moby.rel.freqs.t <- 100 * (sorted.moby.fraq.t/sum(sorted.moby.fraq.t))
sorted.moby.rel.freqs.t["the"]
```

```{r}
#, fig.cap="section 3.2"}
plot(sorted.moby.rel.freqs.t[1:10],
     type = "b",
     xlab = "Top Ten Words",
     ylab = "Percentage of full text",
     xaxt = "n")
axis(1, 1:10,
     labels = names(sorted.moby.rel.freqs.t[1:10]))

```

# Exercises
## 3.1
```{r exercise 3.1}
austen.text.v <- scan(file = "./SupportingMaterials/data/plainText/austen.txt",
               what = "character",
               sep = "\n")
austen.first <- which(austen.text.v == "CHAPTER 1")
austen.last <- which(austen.text.v == "THE END")
austen.last <- austen.last - 1
austen.lines <- austen.text.v[austen.first:austen.last]
austen.text <- paste(austen.lines,
                     collapse = " ")
austen.lower <- tolower(austen.text)
austen.words <- strsplit(austen.lower,
                         "\\W")
austen.words.v <- unlist(austen.words)
not.blanks <- which(austen.words.v != "")
austen.words.v <- austen.words.v[not.blanks]

austen.sorted.freq.table <- sort(table(austen.words.v),
                                 decreasing = TRUE)
head(austen.sorted.freq.table,
     n = 10)
austen.sorted.rel.freq.table <- 100*(austen.sorted.freq.table /
                                             sum(austen.sorted.freq.table))
```
```{r plot for exercise 3.1}
#, fig.cap="exercise 3.1}
plot(austen.sorted.rel.freq.table[1:10],
     type = "b",
     main = "Seence and Sensibility",
     xlab = "Top 10 words",
     ylab = "Percentage",
     xaxt = "n")
axis(1, 1:10,labels = names(austen.sorted.rel.freq.table[1:10]))
```

## Exercise 3.2
```{r exercise 3.2}
unique(c(names(sorted.moby.rel.freqs.t)[1:10],
        names(austen.sorted.rel.freq.table)[1:10]))
```

## Exercise 3.3
```{r exercise 3.3}

```


