---
title: "Chapter 07"
author: "Nick Lauerman"
date: "Started 5/20/2020"
output: 
  pdf_document: 
    fig_caption: yes
    fig_height: 6.5
    fig_width: 6.5
    toc: yes
    toc_depth: 5
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Set up
```{r}
text.v <- scan(file = "./SupportingMaterials/data/plainText/melville.txt",
               what = "character",
               sep = "\n")
start.v <- which(text.v == "CHAPTER 1. Loomings.")
end.v <- which(text.v == "orphan.")
novel.lines.v <- text.v[start.v:end.v]
novel.lines.v <- unlist(novel.lines.v)
chap.positions.v <- grep("^CHAPTER \\d", novel.lines.v)
last.position.v <- length(novel.lines.v)
chap.positions.v <- c(chap.positions.v,
                      last.position.v)
chapter.freqs.l <- list()
chapter.raws.l <- list()
for (i in 1:length(chap.positions.v)) {
  if(i != length(chap.positions.v)){
    chapter.title <- novel.lines.v[chap.positions.v[i]]
    start <- chap.positions.v[i] + 1
    end <- chap.positions.v[i + 1] - 1
    chapter.lines.v <- novel.lines.v[start:end]
    chapter.words.v <- tolower(paste(chapter.lines.v,
                                     collapse = " "))
    chapter.words.l <- strsplit(chapter.words.v,
                                "\\W")
    chapter.words.v <- unlist(chapter.words.l)
    chapter.words.v <- chapter.words.v[which(chapter.words.v != "")]
    chapter.freq.t <- table(chapter.words.v)
    chapter.raws.l[[chapter.title]] <- chapter.freq.t
    chapter.freqs.t.rel <- 100 * (chapter.freq.t/sum(chapter.freq.t))
    chapter.freqs.l[[chapter.title]] <- chapter.freqs.t.rel
  }
}
chapter.lengths.m <- do.call(rbind, lapply(chapter.raws.l, sum))
```

# *sapply*
# A Mini-Conditional Function
```{r}
chapter.hapax.v <- sapply(chapter.raws.l, function(x) sum(x == 1))
chapter.hapax.v
chapter.lengths.m <- do.call(rbind, lapply(chapter.raws.l, sum))
chapter.hapax.v[1] / chapter.lengths.m[1]
chapter.hapax.v[2] / chapter.lengths.m[2]
hapax.percentage <- chapter.hapax.v / chapter.lengths.m
barplot(hapax.percentage,
        beside = TRUE,
        names.arg = seq(1:length(chapter.raws.l)))

```

# Exercises
## 1











