---
title: "Chapter 5"
author: "Nick Lauerman"
date: "Started 5/19/2020"
output: 
  pdf_document: 
    fig_caption: yes
    fig_height: 6.5
    fig_width: 6.5
    number_sections: yes
    toc: yes
    toc_depth: 5
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Data Setup
From Appendex C
```{r}
text.v <- scan(file = "./SupportingMaterials/data/plainText/melville.txt",
               what = "character",
               sep = "\n")
start.v <- which(text.v == "CHAPTER 1. Loomings.")
end.v <- which(text.v == "orphan.")
novel.lines.v <- text.v[start.v:end.v]
novel.lines.v <- unlist(novel.lines.v)

chap.positions.v <- grep("^CHAPTER \\d", novel.lines.v)
last.position.v <- length(novel.lines.v)
chap.positions.v <- c(chap.positions.v,
                      last.position.v)
chapter.freqs.l <- list()
chapter.raws.l <- list()
for (i in 1:length(chap.positions.v)) {
  if(i != length(chap.positions.v)){
    chapter.title <- novel.lines.v[chap.positions.v[i]]
    start <- chap.positions.v[i] + 1
    end <- chap.positions.v[i + 1] - 1
    chapter.lines.v <- novel.lines.v[start:end]
    chapter.words.v <- tolower(paste(chapter.lines.v,
                                     collapse = " "))
    chapter.words.l <- strsplit(chapter.words.v,
                                "\\W")
    chapter.words.v <- unlist(chapter.words.l)
    chapter.words.v <- chapter.words.v[which(chapter.words.v != "")]
    chapter.freq.t <- table(chapter.words.v)
    chapter.raws.l[[chapter.title]] <- chapter.freq.t
    chapter.freqs.t.rel <- 100 * (chapter.freq.t/sum(chapter.freq.t))
    chapter.freqs.l[[chapter.title]] <- chapter.freqs.t.rel
  }
}
whale.l <- lapply(chapter.freqs.l, '[', 'whale')
whales.m <- do.call(rbind, whale.l)
ahab.l <- lapply(chapter.freqs.l, '[', 'ahab')
ahabs.m <- do.call(rbind, ahab.l)
whales.v <- as.vector(whales.m[,1])
ahabs.v <- as.vector(ahabs.m[,1])
whales.ahabs.m <- cbind(whales.v, ahabs.v)
colnames(whales.ahabs.m) <- c("whale",
                              "ahab")
```

# Correlation Analysis
```{r}
whales.ahabs.m[which(is.na(whales.ahabs.m))] <- 0
cor(whales.ahabs.m)

mycor <- cor(whales.ahabs.m[,"whale"],
             whales.ahabs.m[,"ahab"])
mycor
```

# A Word About Data Frames
```{r}
x <- matrix(1, 3, 3)
class(x[1,2])
x[1,2] <- "Sam I am"
x

class(x[1,2])
class(x[1,3])

x <- matrix(1, 3, 3)
x.df <- as.data.frame(x)
x.df
x.df[1,2] <- "Sam I am"
class(x.df[1,2])
class(x.df[1,3])
x.df
```

# Testing Correlation with Randomization
```{r}
cor.data.df <- as.data.frame(whales.ahabs.m)
cor(cor.data.df)

sample(cor.data.df$whale)
cor(sample(cor.data.df$whale),
    cor.data.df$ahab)

mycors.v <- NULL
for (i in 1:10000) {
  mycors.v <- c(mycors.v,
                cor(sample(cor.data.df$whale),
    cor.data.df$ahab))
}
min(mycors.v)
max(mycors.v)
range(mycors.v)
mean(mycors.v)
sd(mycors.v)

h <- hist(mycors.v,
          breaks = 100,
          col = "grey",
          xlab = "Correlation Coefficient",
          main = "Histogram of Random Correlation Coefficients\n with Normal Curve",
          plot = TRUE)
xfit <- seq(min(mycors.v), max(mycors.v), length = 1000)
yfit <- dnorm(xfit,
              mean = mean(mycors.v),
              sd = sd(mycors.v))
yfit <- yfit * diff(h$mids[1:2]) * length(mycors.v)
lines(xfit, yfit, col = "black", lwd = 2 )
```

# Exercises
## 1
```{r}
i.l <- lapply(chapter.freqs.l, '[', 'i')
i.m <- do.call(rbind, i.l)
i.v <- as.vector(i.m[,1])
i.v[which(is.na(i.v))] <- 0

cor.data.df$i <- i.v

my.l <- lapply(chapter.freqs.l, '[', 'my')
my.m <- do.call(rbind, my.l)
my.v <- as.vector(my.m[,1])
my.v[which(is.na(my.v))] <- 0

cor.data.df$my <- my.v

cor(cor.data.df)
```

## 2
```{r}
my.i.m <- cbind(my.v, i.v)
my.i.cor.data.df <- as.data.frame(my.i.m)

cor(my.i.cor.data.df$i,
    my.i.cor.data.df$my)
i.my.cor.v <- NULL
for (i in 1:10000) {
  i.my.cor.v <- c(i.my.cor.v,
                  cor(sample(my.i.cor.data.df$i),
                      my.i.cor.data.df$my))
}
min(i.my.cor.v)
max(i.my.cor.v)
range(i.my.cor.v)
mean(i.my.cor.v)
sd(i.my.cor.v)

```

